listA=[1,4,3,0]
listB=['x','z','t','q']
#listA.sort()
#print(listA)
#print(listA)
#listA.insert(0,100)
#print(listA)
#listA.remove(3)
#print(listA)
#listA.append(7)
#print(listA)
#list=listA+listB
#print(list)
#listB.pop()
#print(listB)
#print(listB)
listA.extend([4,1,6,3])
print(listA)
